version: '3.8'

services:
  nerfstudio:
    build: .
    ports:
      - "7007:7007"
    volumes:
      - "/home/laci/mappings/:/workspace/"
      - "/home/laci/.cache/:/home/user/.cache"
    user: root
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
